default: &default
  adapter: postgresql
  encoding: unicode
  timeout: 5000
  pool: 5
  host: db
  username: dev
  password: dev
#
development:
  <<: *default
  database: dev

test:
  <<: *default
  database: dev_test

production:
  <<: *default
  database: <%= ENV["POSTGRES_DB"] %>
  username: <%= ENV["POSTGRES_USER"] %>
  host: <%= ENV["DB_HOST"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
