default: &default
  adapter: postgresql
  encoding: unicode
  timeout: 5000
  pool: 5
  host: db
  username: dev
  password: dev
#
development:
  <<: *default
  database: dev

test:
  <<: *default
  database: dev_test

production:
  <<: *default
  database: dev_production
  username: dev
  host: <%= ENV["DB_HOST"] %>
  password: <%= ENV["apps_DATABASE_PASSWORD"] %>
