# Name of your application. Used to uniquely configure containers.
service: my-room

# Name of the container image.
image: hodosan/my-room

# Deploy to these servers.
servers:
  web:
    hosts:
      - 123.123.123.123
    labels:
      traefik.http.routers.pdcapro2.rule: Host(`example.com`) || Host(`www.example.com`)
      traefik.http.routers.pdcapro2.entrypoints: websecure
      traefik.http.routers.pdcapro2.tls.certresolver: letsencrypt
    #options:
    #  network: "private"

# Credentials for your image host.
registry:
  username: hodosan

  # Always use an access token rather than real password when possible.
  password:
    - KAMAL_REGISTRY_PASSWORD

# Inject ENV variables into containers (secrets come from .env).
# Remember to run `kamal env push` after making changes!
env:
  clear:
    DB_HOST: 123.123.123.123
  secret:
    - RAILS_MASTER_KEY
    - POSTGRES_PASSWORD
    - POSTGRES_USER
    - POSTGRES_DB


# Use accessory services (secrets come from .env).
accessories:
  db:
    image: postgres
    host: 123.123.123.123
    port: 5432
    env:
      clear:
        # POSTGRES_USER: "dev"
        # POSTGRES_DB: "dev_production"
      secret:
        - POSTGRES_PASSWORD
        - POSTGRES_USER
        - POSTGRES_DB
    directories:
      - pg_data:/var/lib/postgresql/data

# Configure custom arguments for Traefik
traefik:
  options:
    publish:
      - "443:443"
    volume:
      - "/letsencrypt/acme.json:/letsencrypt/acme.json"
    #network: "private"

  args:
    entryPoints.web.address: ":80"
    entryPoints.websecure.address: ":443"
    entryPoints.web.http.redirections.entryPoint.to: websecure
    entryPoints.web.http.redirections.entryPoint.scheme: https
    entryPoints.web.http.redirections.entrypoint.permanent: true
    entrypoints.websecure.http.tls: true
    entrypoints.websecure.http.tls.domains[0].main: "example.com"
    entrypoints.websecure.http.tls.domains[0].sans: "www.example.com"
    certificatesResolvers.letsencrypt.acme.email: "hodosan@example.com"
    certificatesResolvers.letsencrypt.acme.storage: "/letsencrypt/acme.json"
    certificatesResolvers.letsencrypt.acme.httpchallenge: true
    certificatesResolvers.letsencrypt.acme.httpchallenge.entrypoint: web
